/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RiskCouncilRouteImport } from './routes/risk-council'
import { Route as OriginationRouteImport } from './routes/origination'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as CashManagementRouteImport } from './routes/cash-management'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiskCouncilIndexRouteImport } from './routes/risk-council.index'
import { Route as OriginationIndexRouteImport } from './routes/origination.index'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as OriginationNewRouteImport } from './routes/origination.new'
import { Route as OriginationIdRouteImport } from './routes/origination.$id'
import { Route as LoansIdRouteImport } from './routes/loans.$id'
import { Route as RiskCouncilWritedownIdRouteImport } from './routes/risk-council.writedown.$id'
import { Route as RiskCouncilRetermIdRouteImport } from './routes/risk-council.reterm.$id'
import { Route as RiskCouncilEscalateIdRouteImport } from './routes/risk-council.escalate.$id'
import { Route as LoansIdRecordRepaymentRouteImport } from './routes/loans.$id_.record-repayment'
import { Route as LoansIdRecordCouponRouteImport } from './routes/loans.$id_.record-coupon'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCouncilRoute = RiskCouncilRouteImport.update({
  id: '/risk-council',
  path: '/risk-council',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginationRoute = OriginationRouteImport.update({
  id: '/origination',
  path: '/origination',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const CashManagementRoute = CashManagementRouteImport.update({
  id: '/cash-management',
  path: '/cash-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCouncilIndexRoute = RiskCouncilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RiskCouncilRoute,
} as any)
const OriginationIndexRoute = OriginationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OriginationRoute,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoansRoute,
} as any)
const OriginationNewRoute = OriginationNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OriginationRoute,
} as any)
const OriginationIdRoute = OriginationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OriginationRoute,
} as any)
const LoansIdRoute = LoansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LoansRoute,
} as any)
const RiskCouncilWritedownIdRoute = RiskCouncilWritedownIdRouteImport.update({
  id: '/writedown/$id',
  path: '/writedown/$id',
  getParentRoute: () => RiskCouncilRoute,
} as any)
const RiskCouncilRetermIdRoute = RiskCouncilRetermIdRouteImport.update({
  id: '/reterm/$id',
  path: '/reterm/$id',
  getParentRoute: () => RiskCouncilRoute,
} as any)
const RiskCouncilEscalateIdRoute = RiskCouncilEscalateIdRouteImport.update({
  id: '/escalate/$id',
  path: '/escalate/$id',
  getParentRoute: () => RiskCouncilRoute,
} as any)
const LoansIdRecordRepaymentRoute = LoansIdRecordRepaymentRouteImport.update({
  id: '/$id_/record-repayment',
  path: '/$id/record-repayment',
  getParentRoute: () => LoansRoute,
} as any)
const LoansIdRecordCouponRoute = LoansIdRecordCouponRouteImport.update({
  id: '/$id_/record-coupon',
  path: '/$id/record-coupon',
  getParentRoute: () => LoansRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/cash-management': typeof CashManagementRoute
  '/loans': typeof LoansRouteWithChildren
  '/origination': typeof OriginationRouteWithChildren
  '/risk-council': typeof RiskCouncilRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/loans/$id': typeof LoansIdRoute
  '/origination/$id': typeof OriginationIdRoute
  '/origination/new': typeof OriginationNewRoute
  '/loans/': typeof LoansIndexRoute
  '/origination/': typeof OriginationIndexRoute
  '/risk-council/': typeof RiskCouncilIndexRoute
  '/loans/$id/record-coupon': typeof LoansIdRecordCouponRoute
  '/loans/$id/record-repayment': typeof LoansIdRecordRepaymentRoute
  '/risk-council/escalate/$id': typeof RiskCouncilEscalateIdRoute
  '/risk-council/reterm/$id': typeof RiskCouncilRetermIdRoute
  '/risk-council/writedown/$id': typeof RiskCouncilWritedownIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/cash-management': typeof CashManagementRoute
  '/sign-in': typeof SignInRoute
  '/loans/$id': typeof LoansIdRoute
  '/origination/$id': typeof OriginationIdRoute
  '/origination/new': typeof OriginationNewRoute
  '/loans': typeof LoansIndexRoute
  '/origination': typeof OriginationIndexRoute
  '/risk-council': typeof RiskCouncilIndexRoute
  '/loans/$id/record-coupon': typeof LoansIdRecordCouponRoute
  '/loans/$id/record-repayment': typeof LoansIdRecordRepaymentRoute
  '/risk-council/escalate/$id': typeof RiskCouncilEscalateIdRoute
  '/risk-council/reterm/$id': typeof RiskCouncilRetermIdRoute
  '/risk-council/writedown/$id': typeof RiskCouncilWritedownIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/cash-management': typeof CashManagementRoute
  '/loans': typeof LoansRouteWithChildren
  '/origination': typeof OriginationRouteWithChildren
  '/risk-council': typeof RiskCouncilRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/loans/$id': typeof LoansIdRoute
  '/origination/$id': typeof OriginationIdRoute
  '/origination/new': typeof OriginationNewRoute
  '/loans/': typeof LoansIndexRoute
  '/origination/': typeof OriginationIndexRoute
  '/risk-council/': typeof RiskCouncilIndexRoute
  '/loans/$id_/record-coupon': typeof LoansIdRecordCouponRoute
  '/loans/$id_/record-repayment': typeof LoansIdRecordRepaymentRoute
  '/risk-council/escalate/$id': typeof RiskCouncilEscalateIdRoute
  '/risk-council/reterm/$id': typeof RiskCouncilRetermIdRoute
  '/risk-council/writedown/$id': typeof RiskCouncilWritedownIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/cash-management'
    | '/loans'
    | '/origination'
    | '/risk-council'
    | '/sign-in'
    | '/loans/$id'
    | '/origination/$id'
    | '/origination/new'
    | '/loans/'
    | '/origination/'
    | '/risk-council/'
    | '/loans/$id/record-coupon'
    | '/loans/$id/record-repayment'
    | '/risk-council/escalate/$id'
    | '/risk-council/reterm/$id'
    | '/risk-council/writedown/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/cash-management'
    | '/sign-in'
    | '/loans/$id'
    | '/origination/$id'
    | '/origination/new'
    | '/loans'
    | '/origination'
    | '/risk-council'
    | '/loans/$id/record-coupon'
    | '/loans/$id/record-repayment'
    | '/risk-council/escalate/$id'
    | '/risk-council/reterm/$id'
    | '/risk-council/writedown/$id'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/cash-management'
    | '/loans'
    | '/origination'
    | '/risk-council'
    | '/sign-in'
    | '/loans/$id'
    | '/origination/$id'
    | '/origination/new'
    | '/loans/'
    | '/origination/'
    | '/risk-council/'
    | '/loans/$id_/record-coupon'
    | '/loans/$id_/record-repayment'
    | '/risk-council/escalate/$id'
    | '/risk-council/reterm/$id'
    | '/risk-council/writedown/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  CashManagementRoute: typeof CashManagementRoute
  LoansRoute: typeof LoansRouteWithChildren
  OriginationRoute: typeof OriginationRouteWithChildren
  RiskCouncilRoute: typeof RiskCouncilRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-council': {
      id: '/risk-council'
      path: '/risk-council'
      fullPath: '/risk-council'
      preLoaderRoute: typeof RiskCouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origination': {
      id: '/origination'
      path: '/origination'
      fullPath: '/origination'
      preLoaderRoute: typeof OriginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-management': {
      id: '/cash-management'
      path: '/cash-management'
      fullPath: '/cash-management'
      preLoaderRoute: typeof CashManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-council/': {
      id: '/risk-council/'
      path: '/'
      fullPath: '/risk-council/'
      preLoaderRoute: typeof RiskCouncilIndexRouteImport
      parentRoute: typeof RiskCouncilRoute
    }
    '/origination/': {
      id: '/origination/'
      path: '/'
      fullPath: '/origination/'
      preLoaderRoute: typeof OriginationIndexRouteImport
      parentRoute: typeof OriginationRoute
    }
    '/loans/': {
      id: '/loans/'
      path: '/'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof LoansRoute
    }
    '/origination/new': {
      id: '/origination/new'
      path: '/new'
      fullPath: '/origination/new'
      preLoaderRoute: typeof OriginationNewRouteImport
      parentRoute: typeof OriginationRoute
    }
    '/origination/$id': {
      id: '/origination/$id'
      path: '/$id'
      fullPath: '/origination/$id'
      preLoaderRoute: typeof OriginationIdRouteImport
      parentRoute: typeof OriginationRoute
    }
    '/loans/$id': {
      id: '/loans/$id'
      path: '/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof LoansIdRouteImport
      parentRoute: typeof LoansRoute
    }
    '/risk-council/writedown/$id': {
      id: '/risk-council/writedown/$id'
      path: '/writedown/$id'
      fullPath: '/risk-council/writedown/$id'
      preLoaderRoute: typeof RiskCouncilWritedownIdRouteImport
      parentRoute: typeof RiskCouncilRoute
    }
    '/risk-council/reterm/$id': {
      id: '/risk-council/reterm/$id'
      path: '/reterm/$id'
      fullPath: '/risk-council/reterm/$id'
      preLoaderRoute: typeof RiskCouncilRetermIdRouteImport
      parentRoute: typeof RiskCouncilRoute
    }
    '/risk-council/escalate/$id': {
      id: '/risk-council/escalate/$id'
      path: '/escalate/$id'
      fullPath: '/risk-council/escalate/$id'
      preLoaderRoute: typeof RiskCouncilEscalateIdRouteImport
      parentRoute: typeof RiskCouncilRoute
    }
    '/loans/$id_/record-repayment': {
      id: '/loans/$id_/record-repayment'
      path: '/$id/record-repayment'
      fullPath: '/loans/$id/record-repayment'
      preLoaderRoute: typeof LoansIdRecordRepaymentRouteImport
      parentRoute: typeof LoansRoute
    }
    '/loans/$id_/record-coupon': {
      id: '/loans/$id_/record-coupon'
      path: '/$id/record-coupon'
      fullPath: '/loans/$id/record-coupon'
      preLoaderRoute: typeof LoansIdRecordCouponRouteImport
      parentRoute: typeof LoansRoute
    }
  }
}

interface LoansRouteChildren {
  LoansIdRoute: typeof LoansIdRoute
  LoansIndexRoute: typeof LoansIndexRoute
  LoansIdRecordCouponRoute: typeof LoansIdRecordCouponRoute
  LoansIdRecordRepaymentRoute: typeof LoansIdRecordRepaymentRoute
}

const LoansRouteChildren: LoansRouteChildren = {
  LoansIdRoute: LoansIdRoute,
  LoansIndexRoute: LoansIndexRoute,
  LoansIdRecordCouponRoute: LoansIdRecordCouponRoute,
  LoansIdRecordRepaymentRoute: LoansIdRecordRepaymentRoute,
}

const LoansRouteWithChildren = LoansRoute._addFileChildren(LoansRouteChildren)

interface OriginationRouteChildren {
  OriginationIdRoute: typeof OriginationIdRoute
  OriginationNewRoute: typeof OriginationNewRoute
  OriginationIndexRoute: typeof OriginationIndexRoute
}

const OriginationRouteChildren: OriginationRouteChildren = {
  OriginationIdRoute: OriginationIdRoute,
  OriginationNewRoute: OriginationNewRoute,
  OriginationIndexRoute: OriginationIndexRoute,
}

const OriginationRouteWithChildren = OriginationRoute._addFileChildren(
  OriginationRouteChildren,
)

interface RiskCouncilRouteChildren {
  RiskCouncilIndexRoute: typeof RiskCouncilIndexRoute
  RiskCouncilEscalateIdRoute: typeof RiskCouncilEscalateIdRoute
  RiskCouncilRetermIdRoute: typeof RiskCouncilRetermIdRoute
  RiskCouncilWritedownIdRoute: typeof RiskCouncilWritedownIdRoute
}

const RiskCouncilRouteChildren: RiskCouncilRouteChildren = {
  RiskCouncilIndexRoute: RiskCouncilIndexRoute,
  RiskCouncilEscalateIdRoute: RiskCouncilEscalateIdRoute,
  RiskCouncilRetermIdRoute: RiskCouncilRetermIdRoute,
  RiskCouncilWritedownIdRoute: RiskCouncilWritedownIdRoute,
}

const RiskCouncilRouteWithChildren = RiskCouncilRoute._addFileChildren(
  RiskCouncilRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  CashManagementRoute: CashManagementRoute,
  LoansRoute: LoansRouteWithChildren,
  OriginationRoute: OriginationRouteWithChildren,
  RiskCouncilRoute: RiskCouncilRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
