/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RiskCouncilRouteImport } from './routes/risk-council'
import { Route as OriginationRouteImport } from './routes/origination'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as CashManagementRouteImport } from './routes/cash-management'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OriginationIdRouteImport } from './routes/origination.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskCouncilRoute = RiskCouncilRouteImport.update({
  id: '/risk-council',
  path: '/risk-council',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginationRoute = OriginationRouteImport.update({
  id: '/origination',
  path: '/origination',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const CashManagementRoute = CashManagementRouteImport.update({
  id: '/cash-management',
  path: '/cash-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginationIdRoute = OriginationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OriginationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/cash-management': typeof CashManagementRoute
  '/loans': typeof LoansRoute
  '/origination': typeof OriginationRouteWithChildren
  '/risk-council': typeof RiskCouncilRoute
  '/sign-in': typeof SignInRoute
  '/origination/$id': typeof OriginationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/cash-management': typeof CashManagementRoute
  '/loans': typeof LoansRoute
  '/origination': typeof OriginationRouteWithChildren
  '/risk-council': typeof RiskCouncilRoute
  '/sign-in': typeof SignInRoute
  '/origination/$id': typeof OriginationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/cash-management': typeof CashManagementRoute
  '/loans': typeof LoansRoute
  '/origination': typeof OriginationRouteWithChildren
  '/risk-council': typeof RiskCouncilRoute
  '/sign-in': typeof SignInRoute
  '/origination/$id': typeof OriginationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/cash-management'
    | '/loans'
    | '/origination'
    | '/risk-council'
    | '/sign-in'
    | '/origination/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/cash-management'
    | '/loans'
    | '/origination'
    | '/risk-council'
    | '/sign-in'
    | '/origination/$id'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/cash-management'
    | '/loans'
    | '/origination'
    | '/risk-council'
    | '/sign-in'
    | '/origination/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  CashManagementRoute: typeof CashManagementRoute
  LoansRoute: typeof LoansRoute
  OriginationRoute: typeof OriginationRouteWithChildren
  RiskCouncilRoute: typeof RiskCouncilRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-council': {
      id: '/risk-council'
      path: '/risk-council'
      fullPath: '/risk-council'
      preLoaderRoute: typeof RiskCouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origination': {
      id: '/origination'
      path: '/origination'
      fullPath: '/origination'
      preLoaderRoute: typeof OriginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-management': {
      id: '/cash-management'
      path: '/cash-management'
      fullPath: '/cash-management'
      preLoaderRoute: typeof CashManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origination/$id': {
      id: '/origination/$id'
      path: '/$id'
      fullPath: '/origination/$id'
      preLoaderRoute: typeof OriginationIdRouteImport
      parentRoute: typeof OriginationRoute
    }
  }
}

interface OriginationRouteChildren {
  OriginationIdRoute: typeof OriginationIdRoute
}

const OriginationRouteChildren: OriginationRouteChildren = {
  OriginationIdRoute: OriginationIdRoute,
}

const OriginationRouteWithChildren = OriginationRoute._addFileChildren(
  OriginationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  CashManagementRoute: CashManagementRoute,
  LoansRoute: LoansRoute,
  OriginationRoute: OriginationRouteWithChildren,
  RiskCouncilRoute: RiskCouncilRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
