#!/bin/sh
set -eu

env_file="/usr/share/nginx/html/__env.js"
tmp_file="${env_file}.tmp"

{
  printf 'window.__ENV__ = '
  jq -n \
    --arg VITE_API_BASE_URL "${VITE_API_BASE_URL:-}" \
    --arg VITE_EVM_CHAIN_ID "${VITE_EVM_CHAIN_ID:-}" \
    --arg VITE_EVM_RPC_URL "${VITE_EVM_RPC_URL:-}" \
    --arg VITE_DEPOSIT_MANAGER_ADDRESS "${VITE_DEPOSIT_MANAGER_ADDRESS:-}" \
    --arg VITE_WITHDRAWAL_QUEUE_ADDRESS "${VITE_WITHDRAWAL_QUEUE_ADDRESS:-}" \
    --arg VITE_STAKED_PLUSD_ADDRESS "${VITE_STAKED_PLUSD_ADDRESS:-}" \
    --arg VITE_WALLETCONNECT_PROJECT_ID "${VITE_WALLETCONNECT_PROJECT_ID:-}" \
    '{
      VITE_API_BASE_URL: $VITE_API_BASE_URL,
      VITE_EVM_CHAIN_ID: $VITE_EVM_CHAIN_ID,
      VITE_EVM_RPC_URL: $VITE_EVM_RPC_URL,
      VITE_DEPOSIT_MANAGER_ADDRESS: $VITE_DEPOSIT_MANAGER_ADDRESS,
      VITE_WITHDRAWAL_QUEUE_ADDRESS: $VITE_WITHDRAWAL_QUEUE_ADDRESS,
      VITE_STAKED_PLUSD_ADDRESS: $VITE_STAKED_PLUSD_ADDRESS,
      VITE_WALLETCONNECT_PROJECT_ID: $VITE_WALLETCONNECT_PROJECT_ID
    }'
  printf ';\n'
} > "$tmp_file"

mv "$tmp_file" "$env_file"
