#!/bin/sh
set -eu

env_file="/usr/share/nginx/html/__env.js"
tmp_file="${env_file}.tmp"

{
  printf 'window.__ENV__ = '
  jq -n \
    --arg VITE_API_BASE_URL "${VITE_API_BASE_URL:-}" \
    --arg VITE_EVM_CHAIN_ID "${VITE_EVM_CHAIN_ID:-}" \
    --arg VITE_EVM_RPC_URL "${VITE_EVM_RPC_URL:-}" \
    --arg VITE_WALLETCONNECT_PROJECT_ID "${VITE_WALLETCONNECT_PROJECT_ID:-}" \
    --arg VITE_STELLAR_NETWORK_PASSPHRASE "${VITE_STELLAR_NETWORK_PASSPHRASE:-}" \
    --arg VITE_STELLAR_CHAIN_ID "${VITE_STELLAR_CHAIN_ID:-}" \
    --arg VITE_STELLAR_RPC_URL "${VITE_STELLAR_RPC_URL:-}" \
    --arg VITE_STELLAR_USDC_ID "${VITE_STELLAR_USDC_ID:-}" \
    --arg VITE_STELLAR_USDC_CUSTODY_ID "${VITE_STELLAR_USDC_CUSTODY_ID:-}" \
    --arg VITE_STELLAR_LOAN_REGISTRY_ID "${VITE_STELLAR_LOAN_REGISTRY_ID:-}" \
    --arg VITE_STELLAR_LOAN_REGISTRY_EXECUTOR_ID "${VITE_STELLAR_LOAN_REGISTRY_EXECUTOR_ID:-}" \
    --arg VITE_NETWORK_LINKS "${VITE_NETWORK_LINKS:-}" \
    '{
      VITE_API_BASE_URL: $VITE_API_BASE_URL,
      VITE_EVM_CHAIN_ID: $VITE_EVM_CHAIN_ID,
      VITE_EVM_RPC_URL: $VITE_EVM_RPC_URL,
      VITE_WALLETCONNECT_PROJECT_ID: $VITE_WALLETCONNECT_PROJECT_ID,
      VITE_STELLAR_NETWORK_PASSPHRASE: $VITE_STELLAR_NETWORK_PASSPHRASE,
      VITE_STELLAR_CHAIN_ID: $VITE_STELLAR_CHAIN_ID,
      VITE_STELLAR_RPC_URL: $VITE_STELLAR_RPC_URL,
      VITE_STELLAR_USDC_ID: $VITE_STELLAR_USDC_ID,
      VITE_STELLAR_USDC_CUSTODY_ID: $VITE_STELLAR_USDC_CUSTODY_ID,
      VITE_STELLAR_LOAN_REGISTRY_ID: $VITE_STELLAR_LOAN_REGISTRY_ID,
      VITE_STELLAR_LOAN_REGISTRY_EXECUTOR_ID: $VITE_STELLAR_LOAN_REGISTRY_EXECUTOR_ID,
      VITE_NETWORK_LINKS: $VITE_NETWORK_LINKS
    }'
  printf ';\n'
} > "$tmp_file"

mv "$tmp_file" "$env_file"
